function c(){return(document.body?.innerText??"").replace(/\s+/g," ").trim().slice(0,1e3)}function a(){return document.querySelector('meta[name="description"]')?.content?.trim()??""}function l(){const e={title:document.title||"",url:window.location.href,description:a(),content:c()};return{...e,text:`Title: ${e.title}
URL: ${e.url}
Description: ${e.description}
Content: ${e.content}`}}function i(){document.getElementById("intent-lock-blocker")?.remove()}function s(e,n,o){i();const t=document.createElement("div");t.id="intent-lock-blocker",t.style.cssText=["position: fixed","inset: 0","z-index: 2147483647","background: rgba(15, 23, 42, 0.96)","color: white","display: flex","align-items: center","justify-content: center",'font-family: Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',"padding: 24px"].join(";");const r=document.createElement("div");r.style.cssText=["max-width: 520px","width: min(520px, 100%)","border: 1px solid rgba(255,255,255,0.18)","border-radius: 28px","background: linear-gradient(145deg, rgba(99,102,241,0.28), rgba(15,23,42,0.9))","box-shadow: 0 24px 80px rgba(0,0,0,0.45)","padding: 32px","text-align: left"].join(";"),r.innerHTML=`
    <p style="margin: 0 0 10px; color: #c7d2fe; font-size: 12px; font-weight: 800; letter-spacing: 0.18em; text-transform: uppercase;">Intent Lock blocked this page</p>
    <h1 style="margin: 0; font-size: 30px; line-height: 1.1; font-weight: 900;">This page looks off-goal.</h1>
    <p style="margin: 18px 0 0; color: #e5e7eb; font-size: 15px; line-height: 1.6;">Your active goal is <strong>${d(e)}</strong>. This page scored <strong>${n}/100</strong>, below the stricter block threshold of <strong>${o}</strong>.</p>
    <div style="margin-top: 24px; display: flex; gap: 12px; flex-wrap: wrap;">
      <button id="intent-lock-back" style="border: 0; border-radius: 999px; background: white; color: #111827; padding: 12px 18px; font-weight: 800; cursor: pointer;">Go back</button>
      <button id="intent-lock-continue" style="border: 1px solid rgba(255,255,255,0.28); border-radius: 999px; background: rgba(255,255,255,0.08); color: white; padding: 12px 18px; font-weight: 800; cursor: pointer;">Continue intentionally</button>
    </div>
  `,t.append(r),document.documentElement.append(t),r.querySelector("#intent-lock-back")?.addEventListener("click",()=>history.back()),r.querySelector("#intent-lock-continue")?.addEventListener("click",i)}function d(e){const n=document.createElement("span");return n.textContent=e,n.innerHTML}chrome.runtime.onMessage.addListener((e,n,o)=>{if(e.type==="BLOCK_PAGE")return s(e.goal,e.score,e.threshold),o({ok:!0}),!1;if(e.type!=="EXTRACT_PAGE")return!1;try{o({ok:!0,summary:l()})}catch(t){o({ok:!1,error:t instanceof Error?t.message:"Page extraction failed"})}return!1});
